[package]
name = "ihmm"
version = "0.1.0"
authors = ["boris"]
edition = "2018"

[dependencies]

serde_json = "1.0"
rand = "0.6"

trees = {path = "../trees"}

ndarray = "0.12"
ndarray-linalg = { version = "0.10" }
num-traits = "0.2"

[dev-dependencies]
intel-mkl-src = {version = "0.4"}
